### PR TITLE
Create takingframe_from_video&masking

### PR DESCRIPTION
**Pull request by ricsin23**
In this I took a video and captures some frames from it and masked it. This code will capture frame and at the same time masks it.

### CODE REVIEW

**Comment by TejasBob** [comment]
Hey Richa,
I could not understand the purpose of this pull request.
Can you please provide some explanation?

**Comment by ricsin23** [comment]
Hello Tejas

Actually, I saw that in your project you took saved photos and perform
operations on that , so I thought if you have any video and you want to
take frames from that at certain time interval and if you want to take a
mask of it  , then you can do from this code.
Please ignore it if you don't find that purposeful , I am just learning
image processing. That's why I thought it would be better if I work on some
open source projects.
Sorry!! To Bother you.

**Comment by TejasBob** [comment]
Hey Richa,

Glad to know that you found my project useful.
Though your intent is good, your PR is incomplete.
1) I tried running your PR on my local machine, it crashed halfway with some OpenCV error.
2) Also, it doesn't demonstrate how to integrate it with the existing codebase.

Hence, time being I'm closing it, feel free to reopen it whenever you are ready with complete implementation.

**Comment by ricsin23** [comment]
okay !! thanks.

**Pull request closed without merging**
